stages:
  - pre

pre-commit-checks:
  stage: pre
  script:
    - pre-commit run --all-files --verbose --show-diff-on-failure
  image: gitlab-master.nvidia.com:5005/dl/ai-services/python-clients/codeformat:latest
  tags:
    - os/linux
    - type/docker
  only:
    - merge_requests
